import "./globals.scss";

import styles from "./page.module.scss";

import { Montserrat } from "next/font/google";

import Header from "@/libs/components/header/Header";
import Footer from "@/libs/components/footer/Footer";

import { getLayout } from "@/shared/services/api/api";

const montserrat = Montserrat({ subsets: ["cyrillic"] });

export const metadata = {
  title: "Юридичне Бюро Актум",
  description: "Generated by create next app",
  name: "viewport",
  content: "width=device-width, initial-scale=1",
  keywords: "actum",
};

export default async function RootLayout({ children }) {
  const {
    data: {
      attributes: { Header: headers, Footer: footer },
    },
  } = await getLayout();

  return (
    <html lang="uk-UA">
      <body className={montserrat.className}>
        <Header
          logo={headers["LOGO"]}
          nav={headers["Navigation"]}
          routes={headers["Services"]}
        />
        <main className={styles.page}>{children}</main>
        <Footer {...footer} />
      </body>
    </html>
  );
}
