import "./globals.scss";
import { Montserrat } from "next/font/google";

import Header from "@/libs/components/header/Header";
import ContactPanel from "@/libs/components/contactPanel/ContactPanel";

const montserrat = Montserrat({ subsets: ["cyrillic"] });

export const metadata = {
  title: "Юридичне Бюро Актум",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header />
        <ContactPanel />
        <main>{children}</main>
      </body>
    </html>
  );
}
