// import { useEffect, useState, useClient } from "@/libs/hooks/hooks";
import dynamic from "next/dynamic";

import { getHomePage } from "@/shared/services/api/api";

import Hero from "@/libs/components/hero/Hero";
import ContactPanel from "@/libs/components/contactPanel/ContactPanel";

const Direction = dynamic(() =>
  import("@/libs/components/ourDirections/Direction")
);
const Response = dynamic(() => import("@/libs/components/response/Response"));
const AboutCompany = dynamic(() =>
  import("@/libs/components/about_company/AboutCompany")
);

export const metadata = {
  title: "Юридичне Бюро Актум",
  description: "Generated by create next app",
  name: "viewport",
  content: "width=device-width, initial-scale=1",
  keywords: "actum",
};

export default async function Home() {
  // const [isClient, setIsClient] = useState(false);

  // let isFristRender = true;

  // if (typeof window !== "undefined") {
  //   isFristRender = JSON.parse(sessionStorage.getItem("hero_page") || true);
  // }

  // useEffect(() => {
  //   if (isFristRender) {
  //     setTimeout(() => setIsClient(true), 3000);

  //     const scrollY = document.body.style.top;
  //     window.scrollTo(0, parseInt(scrollY || "0") * -1);
  //   } else {
  //     setIsClient(true);
  //   }
  // }, []);

  const {
    data: {
      attributes: { Hero: hero, Directions: directions },
    },
  } = await getHomePage();
  console.log(directions);

  return (
    <>
      <Hero type={"home"} {...hero} />
      <ContactPanel type={"home"} />
      <Direction {...directions} />
      <AboutCompany type={"family"} />
      <Response type={"family"} />
    </>
  );
}
