const {
  API_FAMILY_SERVICES,
  API_CRIME_SERVICES,
  API_RELTY_SERVICES,
  API_ARMY_SERVICES,
  APi_ADMINISTRATIVE_SERVICES,
  API_LAND_SERVICES,
  API_ACCIDENT_SERVICES,
  API_CREDIT_SERVICES,
} = process.env;

const slugs = {
  simein: API_FAMILY_SERVICES,
  krymi: API_CRIME_SERVICES,
  zemelny: API_LAND_SERVICES,
  nerukhomost: API_RELTY_SERVICES,
  administ: APi_ADMINISTRATIVE_SERVICES,
  army: API_ARMY_SERVICES,
  kredytak: API_CREDIT_SERVICES,
  dtp: API_ACCIDENT_SERVICES,
};

export { slugs };
