const {
  API_FAMILY_SERVICES,
  API_CRIME_SERVICES,
  API_RELTY_SERVICES,
  API_ARMY_SERVICES,
  APi_ADMINISTRATIVE_SERVICES,
  API_LAND_SERVICES,
  API_ACCIDENT_SERVICES,
  API_CREDIT_SERVICES,
} = process.env;

const slugs = {
  fami: API_FAMILY_SERVICES,
  API_CRIME_SERVICES: API_CRIME_SERVICES,
  land: API_LAND_SERVICES,
  realty: API_RELTY_SERVICES,
  admin: APi_ADMINISTRATIVE_SERVICES,
  army: API_ARMY_SERVICES,
  credit: API_CREDIT_SERVICES,
  drive: API_ACCIDENT_SERVICES,
};

export { slugs };
