export const cityEnum = {
  Херсон: "kherson",
  Житомир: "zhytomyr",
  Миколаїв: "mykolayv",
  Львів: "lviv",
  "Кривий-ріг": "krivyu_rig",
  Київ: "kyiv",
  Вінниця: "vinitsa",
  Дніпро: "dnipro",
  Донецьк: "doneck",
  Запоріжжя: "zaporishya",
  "Івано-Франківськ": "ivano_frankivsk",
  Кропивницький: "kropevnitsky",
  Луганськ: "lugansk",
  Луцьк: "luck",
  Одеса: "odesa",
  Полтава: "poltava",
  Рівне: "rivne",
  Суми: "sumu",
  Тернопіль: "thernopil",
  Ужгород: "ushgorod",
  Харків: "harkiv",
  Хмельницький: "hmelnickiy",
  Черкаси: "cherkasu",
  Чернівці: "chernivci",
  Чернігів: "chernigiv",
};
